from antlr4 import FileStream, CommonTokenStream, ParseTreeWalker

from .parser_factory import LexerFactory, ParserFactory, ListenerFactory
from ..configuration.router_configuration import RouterConfiguration


class ConfigurationParser:

    @staticmethod
    def parse(configuration_path: str, os_name: str) -> RouterConfiguration:
        router_configuration = RouterConfiguration(configuration_path)

        lexer_class = LexerFactory().get_class_from_os_name(os_name)
        parser_class = ParserFactory().get_class_from_os_name(os_name)
        listener_class = ListenerFactory().get_class_from_os_name(os_name)

        # Parse configuration using ANTLR4 autogenerated parser
        input_stream = FileStream(configuration_path)
        lexer = lexer_class(input_stream)
        stream = CommonTokenStream(lexer)
        parser = parser_class(stream)
        tree = parser.config()
        router_configuration._rule_names = parser.ruleNames

        # Use a custom listener to walk the tree and populate the configuration
        listener = listener_class(router_configuration)
        walker = ParseTreeWalker()
        walker.walk(listener, tree)

        return router_configuration
